
# Site settings
title: Don Dennis
email: don.k.dennis[at]gmail.com
description: Don Dennis metastableB 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  metastableB

# Build settings
markdown: kramdown
port: 8000
default-header-img: /img/1920_1080.jpg
